#!/bin/sh

if grep -q ^VERSION_CODENAME=xenial$ /etc/os-release; then
  exec dbus-run-session -- sh -l -c 'exec egmde --shell-enable-autostart'
else
  exec sh -l -c 'exec egmde --shell-enable-autostart'
fi

