name: egmde
adopt-info: egmde
summary: A minimal example Mir based desktop shell
description: A minimal example Mir based desktop shell
confinement: classic
base: core20

apps:
  egmde:
    command: bin/egmde.launcher
    environment:
      # Prep for Mir
      MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
      MIR_SERVER_XWAYLAND_PATH: ${SNAP}/usr/bin/Xwayland
      MIR_SERVER_ENABLE_X11: 1
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      EGMDE_LAUNCH_PREFIX: "env -u LD_LIBRARY_PATH -u __EGL_VENDOR_LIBRARY_DIRS -u LIBGL_DRIVERS_PATH -u EGMDE_LAUNCH_PREFIX --"
      PATH: ${PATH}:/snap/bin
      XDG_DATA_DIRS: ${XDG_DATA_DIRS}:~/.local/share
      XDG_CURRENT_DESKTOP: egmde

parts:
  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      snapcraftctl pull

  egmde:
    after: [recipe-version, ppa-setup]
    override-pull: |
      snapcraftctl pull
      server_version=`git rev-list --count HEAD`
      mir_version=`LANG=C apt-cache policy mir-graphics-drivers-desktop | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $server_version-mir$mir_version-snap$recipe_version
      if echo $mir_version | grep dev; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    override-build: |
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl build
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
      - libwayland-dev
      - libxkbcommon-dev
      - g++
      - make
    stage-packages:
      - libmiral4
      - mir-graphics-drivers-desktop
      - libfreetype6
      - fonts-freefont-ttf
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig

  launcher:
    plugin: dump
    source: glue
    organize:
      egmde.launcher: bin/
      egmde.desktop: bin/

  mesa:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    - libtinfo5
    build-attributes:
    - no-patchelf # Otherwise snapcraft may strip the build ID and cause the driver to crash
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig

  xwayland:
    plugin: nil
    build-attributes:
      - no-patchelf
    stage-packages:
      - xwayland
      - libbz2-1.0
