name: egmde
version: egmde
version-script: |
  LANG=C apt-cache policy libmiral-dev | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/0.4-mir\1/p'
summary: A minimal example Mir based desktop shell
description: A minimal example Mir based desktop shell
confinement: classic
grade: devel
base: core18

apps:
  egmde:
    command: bin/egmde.launcher
    environment:
      # Prep for Mir
      MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
      MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      EGMDE_LAUNCH_PREFIX: "env -u __EGL_VENDOR_LIBRARY_DIRS --"

parts:
  ppa-mir-release:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -yu ppa:mir-team/release
      # We shouldn't need to install stuff here, but it seems to fix intermittent build failures
      sudo apt --assume-yes install libmiral-dev mir-graphics-drivers-desktop
      sudo apt clean
      snapcraftctl pull

  egmde:
    after: [ppa-mir-release]
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
    stage-packages:
      - mir-graphics-drivers-desktop
      - libmiral3

  launcher:
    plugin: dump
    source: glue
    organize:
      egmde.launcher: bin/
      egmde.desktop: bin/

  mesa:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
