name: egmde
version: egmde
version-script: |
  LANG=C apt-cache policy libmiral-dev | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/0.3-\1/p'
summary: A minimal example Mir based desktop shell
description: A minimal example Mir based desktop shell
confinement: classic
grade: devel
base: core18

apps:
  egmde:
    command: bin/egmde.launcher
    environment:
      # Prep for Mir
      MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
      MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
      # Prep for Qt wayland
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/

parts:
  egmde:
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
    stage-packages:
      - mir-graphics-drivers-desktop
      - libmiral3

  launcher:
    plugin: dump
    source: glue
    organize:
      egmde.launcher: bin/
      egmde.desktop: bin/

  wayland:
    plugin: nil
    stage-packages:
      - qtwayland5
