name: egmde
adopt-info: egmde-snap
summary: A minimal example Mir based desktop shell
description: A minimal example Mir based desktop shell
confinement: classic
grade: stable
base: core18

environment:
  # Prep for Mir
  MIR_CLIENT_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/client-platform
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  EGMDE_LAUNCH_PREFIX: "env -u __EGL_VENDOR_LIBRARY_DIRS --"

apps:
  egmde:
    command: bin/egmde.launcher

parts:
  ppa-mir-release:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -yu ppa:mir-team/release
      # We shouldn't need to install stuff here, but it seems to fix intermittent build failures
      sudo apt --assume-yes install libmiral-dev mir-graphics-drivers-desktop
      snapcraftctl pull

  egmde:
    after: [ppa-mir-release]
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
      - libwayland-dev
      - libxkbcommon-dev
    stage-packages:
      - mir-graphics-drivers-desktop
      - libmiral3
      - libfreetype6
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig

  launcher:
    plugin: dump
    source: glue
    organize:
      egmde.launcher: bin/
      egmde.desktop: bin/

  egmde-snap:
    after: [ppa-mir-release, egmde]
    plugin: nil
    source: .
    source-type: git
    override-build: |
      recipe_version=-snap$(git rev-list --count HEAD)
      server_version=$(git -C ../../egmde/src rev-list --count HEAD)
      mir_version=`LANG=C apt-cache policy libmircore1 | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/-mir\1/p'`
      snapcraftctl set-version $server_version$mir_version$recipe_version

  mesa:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig
