name: egmde
adopt-info: egmde
summary: A minimal example Mir based desktop shell
description: A minimal example Mir based desktop shell
confinement: classic
base: core20

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  egmde:
    command: bin/egmde.launcher
    environment:
      # Prep for Mir
      MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
      MIR_SERVER_XWAYLAND_PATH: ${SNAP}/usr/bin/Xwayland
      MIR_SERVER_APP_ENV: "GDK_BACKEND=wayland,x11:QT_QPA_PLATFORM=wayland:SDL_VIDEODRIVER=wayland:-QT_QPA_PLATFORMTHEME:NO_AT_BRIDGE=1:QT_ACCESSIBILITY:QT_LINUX_ACCESSIBILITY_ALWAYS_ON:_JAVA_AWT_WM_NONREPARENTING=1:MOZ_ENABLE_WAYLAND=1:-GTK_MODULES:-OOO_FORCE_DESKTOP:-GNOME_ACCESSIBILITY:-__EGL_VENDOR_LIBRARY_DIRS:-LIBGL_DRIVERS_PATH"
      MIR_SERVER_ENABLE_X11: 1
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      PATH: ${PATH}:/snap/bin
      XDG_DATA_DIRS: ${XDG_DATA_DIRS}:~/.local/share
      XDG_CURRENT_DESKTOP: egmde

parts:
  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      snapcraftctl pull

  egmde:
    after: [recipe-version, ppa-setup]
    override-pull: |
      snapcraftctl pull
      server_version=`git rev-list --count HEAD`
      mir_version=`LANG=C apt-cache policy mir-graphics-drivers-desktop | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $server_version-mir$mir_version-snap$recipe_version
      if echo $mir_version | grep -e '+dev' -e '~rc' -q; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    override-build: |
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl build
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
      - libwayland-dev
      - libxkbcommon-dev
      - g++
      - make
    stage-packages:
      - libmiral4
      - mir-graphics-drivers-desktop
      - libfreetype6
      - fonts-freefont-ttf
    prime:
      - -lib/udev
      - -usr/doc
      - -usr/doc-base
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libdrm
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pkgconfig

  launcher:
    plugin: dump
    source: glue
    organize:
      egmde.launcher: bin/
      egmde.desktop: bin/
      swaybg.launcher: bin/
    override-build: |
      snapcraftctl build
      sed s/\$\{SNAPCRAFT_ARCH_TRIPLET}/${SNAPCRAFT_ARCH_TRIPLET}/g --in-place $SNAPCRAFT_PART_INSTALL/swaybg.launcher

  mesa-patchelf:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    - libtinfo5
    # included in this part because it tries to pull in mesa bits
    - xwayland
    - swaybg
    - waybar
    stage:
      # The libraries in .../dri need no-patchelf, so they come from the mesa-unpatched part
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

  mesa-no-patchelf:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
    build-attributes:
      - no-patchelf # Otherwise snapcraft may strip the build ID and cause the driver to crash
    stage:
      # Only the libraries in .../dri need to not be patched, the rest come from the mesa part
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri