name: egmde
version: egmde
version-script: |
  LANG=C apt-cache policy libmiral-dev | sed -rne 's/^\s+Candidate:\s+(.*)-[^-]+$/0.1-miral\1/p'
summary: A minimal example Mir based desktop shell
description: A minimal example Mir based desktop shell
confinement: classic
grade: devel
base: core18

apps:
  egmde:
    command: bin/egmde.launcher
    environment:
      XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
      XCURSOR_PATH:    $SNAP/icons
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d

parts:
  egmde:
    plugin: cmake
    source: https://github.com/AlanGriffiths/egmde.git
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
    stage-packages:
      - fonts-freefont-ttf
      - mir-graphics-drivers-desktop
      - libmiral3

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]
    organize:
      usr/share/icons/DMZ-White: icons/default
    prime:
     - icons/default

  launcher:
    plugin: dump
    source: glue
    organize:
      egmde.launcher: bin/
      egmde.desktop: bin/

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri

  wayland:
    plugin: nil
    stage-packages:
      - qtwayland5
