#!/bin/sh

mkdir -p /usr/share/wayland-sessions/
cp "$SNAP"/bin/egmde.desktop /usr/share/wayland-sessions/egmde.desktop
if grep -q ^VERSION_CODENAME=xenial$ /etc/os-release; then
  # Hack egmde.desktop to work on Xenial
  sed "s/Exec=sh/Exec=dbus-run-session sh/g" --in-place /usr/share/wayland-sessions/egmde.desktop
fi

for x in "x86_64-linux-gnu" "aarch64-linux-gnu" "arm-linux-gnueabihf";
do
  if [ -e "$SNAP/usr/lib/$x" ]; then ARCH_TRIPLET="$x"; fi
done

export GDK_PIXBUF_MODULEDIR="$SNAP/usr/lib/${ARCH_TRIPLET}/gdk-pixbuf-2.0/2.10.0/loaders"
export GDK_PIXBUF_MODULE_FILE="$SNAP_COMMON/loaders.cache"
"$SNAP/usr/lib/${ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" > "$GDK_PIXBUF_MODULE_FILE"
