#!/bin/bash

mkdir -p /usr/share/wayland-sessions/
cp $SNAP/bin/egmde.desktop /usr/share/wayland-sessions/egmde.desktop

# Ensure Wayland support is available for Qt apps
if [ "$(sed -Ene 's/^ID=(.*)/\1/p' /etc/os-release)" = "ubuntu" ]; then
  apt --assume-yes install qtwayland5
elif [ "$(sed -Ene 's/^ID=(.*)/\1/p' /etc/os-release)" = "fedora" ]; then
  env -u LD_LIBRARY_PATH dnf --assumeyes  install qt5-qtwayland
fi
