#!/bin/sh

mkdir -p /usr/share/wayland-sessions/
cp "$SNAP"/bin/egmde.desktop /usr/share/wayland-sessions/egmde.desktop

for x in "x86_64-linux-gnu" "aarch64-linux-gnu" "arm-linux-gnueabihf";
do
  if [ -e "$SNAP/usr/lib/$x" ]; then ARCH_TRIPLET="$x"; fi
done

export GDK_PIXBUF_MODULEDIR="$SNAP/usr/lib/${ARCH_TRIPLET}/gdk-pixbuf-2.0/2.10.0/loaders"
export GDK_PIXBUF_MODULE_FILE="$SNAP_COMMON/loaders.cache"
$SNAP/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $GDK_PIXBUF_MODULE_FILE
