#!/bin/sh

mkdir -p /usr/share/wayland-sessions/
cp "$SNAP"/bin/egmde.desktop /usr/share/wayland-sessions/egmde.desktop

# Ensure Wayland support is available for Qt apps
if command -v apt > /dev/null 2>&1
then
  apt-get update
  apt-get --assume-yes install qtwayland5
elif command -v dnf > /dev/null 2>&1
then
  dnf --assumeyes install qt5-qtwayland
fi
